#
# Copyright (c) 2021-2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/castor.
#
# SPDX-License-Identifier: Apache-2.0
#
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-byte-order-marker
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.6.0
    hooks:
      - id: pretty-format-java
        args: [--autofix]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        args:
          - --wrap
          - "80"
        additional_dependencies:
          - mdformat-gfm
        exclude: ^.*/vendor/.*|.*/3RD-PARTY-LICENSES/.*$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
        exclude: ^.*/vendor/.*|.*/3RD-PARTY-LICENSES/.*|castor-service/charts/castor/README.md$

  - repo: https://github.com/yoheimuta/protolint
    rev: v0.43.1
    hooks:
      - id: protolint
        args: [-fix]
        config:
          disabled_rules:
            - ENUM_FIELD_NAMES_PREFIX
            - ENUM_FIELD_NAMES_UPPER_SNAKE_CASE
            - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
            - ENUM_NAMES_UPPER_CAMEL_CASE
