// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        v4.22.2
// source: tuples_upload.proto

package common_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcUploadTupleChunkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkId   string `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	TupleType string `protobuf:"bytes,2,opt,name=tuple_type,json=tupleType,proto3" json:"tuple_type,omitempty"`
	Tuples    []byte `protobuf:"bytes,3,opt,name=tuples,proto3" json:"tuples,omitempty"`
}

func (x *GrpcUploadTupleChunkRequest) Reset() {
	*x = GrpcUploadTupleChunkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuples_upload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcUploadTupleChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcUploadTupleChunkRequest) ProtoMessage() {}

func (x *GrpcUploadTupleChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tuples_upload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcUploadTupleChunkRequest.ProtoReflect.Descriptor instead.
func (*GrpcUploadTupleChunkRequest) Descriptor() ([]byte, []int) {
	return file_tuples_upload_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcUploadTupleChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *GrpcUploadTupleChunkRequest) GetTupleType() string {
	if x != nil {
		return x.TupleType
	}
	return ""
}

func (x *GrpcUploadTupleChunkRequest) GetTuples() []byte {
	if x != nil {
		return x.Tuples
	}
	return nil
}

type GrpcUploadTupleChunkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid         string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	IsSuccess    bool   `protobuf:"varint,3,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
}

func (x *GrpcUploadTupleChunkResponse) Reset() {
	*x = GrpcUploadTupleChunkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuples_upload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcUploadTupleChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcUploadTupleChunkResponse) ProtoMessage() {}

func (x *GrpcUploadTupleChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tuples_upload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcUploadTupleChunkResponse.ProtoReflect.Descriptor instead.
func (*GrpcUploadTupleChunkResponse) Descriptor() ([]byte, []int) {
	return file_tuples_upload_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcUploadTupleChunkResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GrpcUploadTupleChunkResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GrpcUploadTupleChunkResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

var File_tuples_upload_proto protoreflect.FileDescriptor

var file_tuples_upload_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x22, 0x69, 0x6f, 0x2e, 0x63, 0x61, 0x72, 0x62, 0x79, 0x6e,
	0x65, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x2e, 0x63, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x22, 0x6f, 0x0a, 0x1b, 0x47, 0x72, 0x70,
	0x63, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x75, 0x6e,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x75, 0x6e,
	0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x22, 0x76, 0x0a, 0x1c, 0x47, 0x72,
	0x70, 0x63, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x42, 0x0d, 0x5a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tuples_upload_proto_rawDescOnce sync.Once
	file_tuples_upload_proto_rawDescData = file_tuples_upload_proto_rawDesc
)

func file_tuples_upload_proto_rawDescGZIP() []byte {
	file_tuples_upload_proto_rawDescOnce.Do(func() {
		file_tuples_upload_proto_rawDescData = protoimpl.X.CompressGZIP(file_tuples_upload_proto_rawDescData)
	})
	return file_tuples_upload_proto_rawDescData
}

var file_tuples_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tuples_upload_proto_goTypes = []interface{}{
	(*GrpcUploadTupleChunkRequest)(nil),  // 0: io.carbynestack.castor.common.grpc.GrpcUploadTupleChunkRequest
	(*GrpcUploadTupleChunkResponse)(nil), // 1: io.carbynestack.castor.common.grpc.GrpcUploadTupleChunkResponse
}
var file_tuples_upload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tuples_upload_proto_init() }
func file_tuples_upload_proto_init() {
	if File_tuples_upload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tuples_upload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcUploadTupleChunkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuples_upload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcUploadTupleChunkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tuples_upload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tuples_upload_proto_goTypes,
		DependencyIndexes: file_tuples_upload_proto_depIdxs,
		MessageInfos:      file_tuples_upload_proto_msgTypes,
	}.Build()
	File_tuples_upload_proto = out.File
	file_tuples_upload_proto_rawDesc = nil
	file_tuples_upload_proto_goTypes = nil
	file_tuples_upload_proto_depIdxs = nil
}
